
echo "Vadstena.geodataProcessorWorker = function() { " | cat - engine/browser/geoWorkerGlobals.js engine/browser/geoWorkerStyle.js engine/browser/geoWorkerLineString.js engine/browser/geoWorkerPointArray.js engine/browser/geoWorkerText.js engine/browser/geoWorkerMain.js > engine/browser/geodataWorkerTmp.js
echo "};">> engine/browser/geodataWorkerTmp.js 

cat engine/libs/proj4.js engine/libs/poly2tri.js engine/browser/_minify.js engine/browser/matrix.js engine/browser/math.js engine/browser/utility.js engine/browser/config.js engine/browser/bbox.js engine/browser/cache.js engine/browser/camera.js engine/browser/geodataWorkerTmp.js engine/browser/geodataProcessor.js engine/browser/gpuFont.js engine/browser/gpuText.js engine/browser/gpuGeodata.js engine/browser/gpuGroup.js engine/browser/gpuLine.js engine/browser/gpuPixelLine.js engine/browser/gpuPolygon.js engine/browser/gpuDevice.js engine/browser/gpuBBox.js engine/browser/gpuMesh.js engine/browser/gpuProgram.js engine/browser/gpuShaders.js engine/browser/gpuTexture.js engine/browser/gpuTile.js engine/browser/layer.js engine/browser/layerOld.js engine/browser/layerTiled.js engine/browser/layerTiledDraw.js engine/browser/layerTerrain.js engine/browser/layerTerrainDraw.js engine/browser/layerTerrainSurface.js engine/browser/mesh.js engine/browser/planet.js engine/browser/renderer.js engine/browser/rendererInit.js engine/browser/rendererCamera.js engine/browser/rendererDraw.js engine/browser/rendererDrawLayers.js engine/browser/rendererDrawTiles.js engine/browser/tileId.js engine/browser/tileTerrain.js engine/browser/tileGeodata.js engine/browser/tileMetadata.js engine/browser/platform.js engine/browser/browser.js engine/autopilot/autopilot.js engine/interface/builder.js engine/interface/interface.js engine/interface/info.js engine/interface/input.js engine/interface/input-touch.js engine/interface/panels.js engine/interface/compass.js engine/interface/gis.js engine/interface/places.js engine/interface/stats.js engine/interface/websockets.js engine/import/kmlLoad.js engine/import/osmLoad.js engine/import/mglLoad.js engine/engine.js > build/engine-v1-merge.js
cp engine/interface/builder.css build/engine-v1.css
java -jar compiler/compiler.jar --compilation_level ADVANCED_OPTIMIZATIONS --js engine/browser/_minify.js engine/browser/matrix.js engine/browser/math.js engine/browser/utility.js engine/browser/config.js engine/browser/bbox.js engine/browser/cache.js engine/browser/camera.js engine/browser/geodataWorkerTmp.js engine/browser/geodataProcessor.js engine/browser/gpuFont.js engine/browser/gpuText.js engine/browser/gpuGeodata.js engine/browser/gpuGroup.js engine/browser/gpuLine.js engine/browser/gpuPixelLine.js engine/browser/gpuPolygon.js engine/browser/gpuDevice.js engine/browser/gpuBBox.js engine/browser/gpuMesh.js engine/browser/gpuProgram.js engine/browser/gpuShaders.js engine/browser/gpuTexture.js engine/browser/gpuTile.js engine/browser/layer.js engine/browser/layerOld.js engine/browser/layerTiled.js engine/browser/layerTiledDraw.js engine/browser/layerTerrain.js engine/browser/layerTerrainDraw.js engine/browser/layerTerrainSurface.js engine/browser/mesh.js engine/browser/planet.js engine/browser/renderer.js engine/browser/rendererInit.js engine/browser/rendererCamera.js engine/browser/rendererDraw.js engine/browser/rendererDrawLayers.js engine/browser/rendererDrawTiles.js engine/browser/tileId.js engine/browser/tileTerrain.js engine/browser/tileGeodata.js engine/browser/tileMetadata.js engine/browser/platform.js engine/browser/browser.js engine/autopilot/autopilot.js engine/interface/builder.js engine/interface/interface.js engine/interface/info.js engine/interface/input.js engine/interface/input-touch.js engine/interface/panels.js engine/interface/compass.js engine/interface/gis.js engine/interface/places.js engine/interface/stats.js engine/interface/websockets.js engine/import/kmlLoad.js engine/import/osmLoad.js engine/import/mglLoad.js engine/engine.js --js_output_file build/engine-v1-tmp.js
cat engine/libs/proj4.js engine/libs/poly2tri.min.js build/engine-v1-tmp.js  > build/engine-v1.js
rm build/engine-v1-tmp.js
rm engine/browser/geodataWorkerTmp.js 
cp build/engine-v1.js build/engine-latest.js
cp build/engine-v1.css build/engine-latest.css
 



